version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Verify.Xunit
    versions:
    - 10.9.0
    - 11.0.1
    - 11.0.2
    - 11.2.0
    - 11.4.0
    - 11.8.0
  - dependency-name: Verify
    versions:
    - 10.5.1
    - 10.9.0
    - 11.0.0
    - 11.0.1
    - 11.0.2
    - 11.2.0
    - 11.4.0
    - 11.8.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
  - dependency-name: Verify.Selenium
    versions:
    - 0.9.0
  - dependency-name: Microsoft.AspNetCore.Components.WebAssembly.DevServer
    versions:
    - 5.0.3
  - dependency-name: Microsoft.AspNetCore.Components
    versions:
    - 5.0.3
  - dependency-name: Microsoft.AspNetCore.Components.WebAssembly
    versions:
    - 5.0.3
  - dependency-name: Microsoft.AspNetCore.Components.Web
    versions:
    - 5.0.3
