<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="MarkdownSnippets.MsBuild" Version="28.5.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components" Version="10.0.12" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.12" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="ProjectDefaults" Version="1.0.184" />
    <PackageVersion Include="Sbom" Version="0.3.1" />
    <PackageVersion Include="Verify" Version="33.3.3" />
    <PackageVersion Include="Verify.AngleSharp" Version="5.1.2" />
    <PackageVersion Include="Verify.XunitV3" Version="33.3.3" />
    <PackageVersion Include="xunit.v3" Version="4.0.2" />
    <PackageVersion Include="Argon" Version="0.38.2" />
    <PackageVersion Include="DiffEngine" Version="20.8.1" />
    <PackageVersion Include="EmptyFiles" Version="8.20.1" />
    <PackageVersion Include="SimpleInfoName" Version="3.2.1" />
  </ItemGroup>
</Project>
